---
- name: be sure redis is installed.
  yum:
    name: redis
    state: installed
  tags: redis

- name: be sure redis is able to connect by remote hosts.
  lineinfile:
    dest: /etc/redis.conf
    regexp: "^bind 127.0.0.1$"
    line: bind 0.0.0.0
    state: present
    backrefs: yes
  notify: restart redis
  tags: redis

- name: be sure password authentication of redis is disabled.
  lineinfile:
    dest: /etc/redis.conf
    regexp: "^requirepass {{ redis.password }}"
    line: "# requirepass foobared"
    state: present
    backrefs: yes
  notify: restart redis
  tags: redis

- name: be sure redis is started and enabled.
  service:
    name: redis
    state: started
    enabled: yes
  notify: restart firewalld
  tags: redis
